/**
 * Round-trip parity — the cross-language false-reject invariant.
 *
 * The fixture holds the client RegexScrubber's output for every
 * deterministic-tier corpus input (generated by
 * scripts/regen_roundtrip_fixture.py, freshness-pinned by
 * tests/test_roundtrip_fixture.py). A correctly client-scrubbed upload must
 * never be rejected by the server gate, so checkPii() must return null on each.
 *
 * This is the only end-to-end guard on the hand-synced placeholder grammar: the
 * client's emit vocabulary ([URL:host], [NAME_1], [EMAIL], ...) vs the Worker's
 * PII_ALLOWLIST / PII_ALLOWLIST_DYNAMIC. If they drift — e.g. the scrubber emits
 * a placeholder the gate doesn't allowlist, like [URL:192.168.1.1] whose inner
 * IP would trip the IPv4 detector — an honest upload bounces, and this fails.
 */

import { describe, it, expect } from "vitest";
import { checkPii } from "../src/content-filter.js";
import FIXTURE from "./fixtures/scrubbed_corpus.json";

describe("round-trip — client scrub output passes the Worker PII gate", () => {
  it("fixture is non-empty", () => {
    expect(FIXTURE.length).toBeGreaterThan(0);
  });

  for (const { id, scrubbed } of FIXTURE) {
    it(id, () => {
      expect(checkPii(scrubbed)).toBeNull();
    });
  }
});
