#!/usr/bin/env python3
"""Regenerate the secret-scrubber stopword set from its pinned sources.

The stopword set gates the dictionary-based false-positive rejector in BOTH
runtimes (``src/common_parlance/_stopwords.py`` and ``worker/src/stopwords.js``).
It must stay byte-identical between them (see ``tests/test_stopwords_parity.py``)
and reproducible from clean-licensed sources rather than being an opaque blob.

Recipe (verified to reproduce the committed set exactly):

    STOPWORDS = G  ∪  gwordlist[:N]  ∪  FLOOR

where, all filtered to lowercase ``^[a-z]+$`` of length >= 4:

  * G        = gitleaks ``DefaultStopWords`` (MIT)        -> dev/tech vocabulary
  * gwordlist= the top N most-frequent words of hackerb9/gwordlist
               ``frequency-alpha-alldicts.txt`` (CC-BY 3.0) -> general English
  * FLOOR    = a few common code-identifier words the gwordlist lemmatizer drops

Sources are pinned by commit SHA below; bump them deliberately and re-review the
resulting diff. Attribution lives in the repo ``NOTICE`` file.

Usage (needs network to fetch the two sources):

    python scripts/regen_stopwords.py --check    # verify committed == regenerated
    python scripts/regen_stopwords.py --write     # rewrite both runtime files
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path

# --- Pinned sources -------------------------------------------------------

GITLEAKS_SHA = "8ad8470035d31a209322c580153b45c18e21b980"
GITLEAKS_URL = (
    "https://raw.githubusercontent.com/gitleaks/gitleaks/"
    f"{GITLEAKS_SHA}/cmd/generate/config/rules/stopwords.go"
)

GWORDLIST_SHA = "5e9902468ab09802474884c3df00d77463e5cb24"
GWORDLIST_URL = (
    "https://raw.githubusercontent.com/hackerb9/gwordlist/"
    f"{GWORDLIST_SHA}/frequency-alpha-alldicts.txt"
)

# Number of most-frequent gwordlist words to take. 5200 is the cutoff just below
# the first frequency-ranked word that is not part of the curated set ("onset");
# raising it would pull in words the original generation excluded.
GWORDLIST_TOP_N = 5200

# Common code-identifier words the gwordlist lemmatizer drops (plurals, etc.)
# that aren't in gitleaks either. Added explicitly so they aren't treated as
# high-entropy secrets.
FLOOR = frozenset(
    {"attempts", "delegate", "modules", "recommender", "singleton", "wrapped"}
)

_ROOT = Path(__file__).resolve().parent.parent
_PY_PATH = _ROOT / "src" / "common_parlance" / "_stopwords.py"
_JS_PATH = _ROOT / "worker" / "src" / "stopwords.js"


def _keep(word: str) -> bool:
    return len(word) >= 4 and re.fullmatch(r"[a-z]+", word) is not None


def _fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=120) as resp:  # noqa: S310
        return resp.read().decode("utf-8")


def _gitleaks_words(text: str) -> set[str]:
    body = text[text.index("DefaultStopWords") :]
    return {w for w in re.findall(r'"([^"]+)"', body) if _keep(w)}


def _gwordlist_top(text: str, n: int) -> set[str]:
    out: list[str] = []
    seen: set[str] = set()
    for line in text.splitlines():
        if line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        word = parts[1].lower()
        if _keep(word) and word not in seen:
            seen.add(word)
            out.append(word)
            if len(out) >= n:
                break
    return set(out)


def build_stopwords() -> set[str]:
    gitleaks = _gitleaks_words(_fetch(GITLEAKS_URL))
    gwordlist = _gwordlist_top(_fetch(GWORDLIST_URL), GWORDLIST_TOP_N)
    return gitleaks | gwordlist | set(FLOOR)


# --- Emitters -------------------------------------------------------------

_PROVENANCE = [
    "Generated by scripts/regen_stopwords.py — do not edit by hand.",
    "",
    "Union of two clean-license sources, filtered to lowercase ^[a-z]+$ of",
    "length >= 4 (attribution in the repo NOTICE):",
    "",
    f"  * gitleaks DefaultStopWords (MIT) @ {GITLEAKS_SHA[:12]}",
    f"  * top {GWORDLIST_TOP_N} words of hackerb9/gwordlist (CC-BY 3.0) @ "
    f"{GWORDLIST_SHA[:12]}",
    "  * a small floor of code-identifier words the lemmatizer drops",
]


def _fill(words: list[str], indent: str, width: int = 88) -> list[str]:
    lines: list[str] = []
    cur = ""
    for w in words:
        token = f'"{w}",'
        if not cur:
            cur = indent + token
        elif len(cur) + 1 + len(token) <= width:
            cur = cur + " " + token
        else:
            lines.append(cur)
            cur = indent + token
    if cur:
        lines.append(cur)
    return lines


def render_python(words: list[str]) -> str:
    doc = "\n".join(_PROVENANCE)
    body = "\n".join(_fill(words, "    "))
    return f'"""{doc}\n"""\n\nSTOPWORDS = frozenset({{\n{body}\n}})\n'


def render_js(words: list[str]) -> str:
    header = "\n".join("// " + line if line else "//" for line in _PROVENANCE)
    body = "\n".join(_fill(words, "  "))
    return f"{header}\n\nexport const STOPWORDS = new Set([\n{body}\n]);\n"


def _committed_set(path: Path, pattern: str) -> set[str]:
    text = path.read_text()
    text = text[re.search(pattern, text).start() :]
    return set(re.findall(r'"([a-z]+)"', text))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    group = ap.add_mutually_exclusive_group()
    group.add_argument(
        "--check",
        action="store_true",
        help="verify the committed files match the regenerated set (default)",
    )
    group.add_argument(
        "--write", action="store_true", help="rewrite both runtime files"
    )
    args = ap.parse_args()

    words = sorted(build_stopwords())
    print(f"built {len(words)} stopwords from pinned sources", file=sys.stderr)

    if args.write:
        _PY_PATH.write_text(render_python(words))
        _JS_PATH.write_text(render_js(words))
        print(f"wrote {_PY_PATH} and {_JS_PATH}", file=sys.stderr)
        return 0

    # Default: --check
    built = set(words)
    ok = True
    for path, pattern in ((_PY_PATH, r"frozenset\("), (_JS_PATH, r"new Set\(")):
        committed = _committed_set(path, pattern)
        extra = built - committed
        missing = committed - built
        if extra or missing:
            ok = False
            print(
                f"DRIFT in {path.name}: {len(extra)} extra {sorted(extra)[:5]}, "
                f"{len(missing)} missing {sorted(missing)[:5]}",
                file=sys.stderr,
            )
        else:
            print(f"OK {path.name}: {len(committed)} words match", file=sys.stderr)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
